### ISSUE TITLE
dns server runs away

### ISSUE THREAD

**Issue by hawkingrei** [hawkingrei/g53#10]
github.com/hawkingrei/g53/servers.(*DNSServer).(github.com/hawkingrei/g53/servers.handleRequest)-fm(0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:56 +0x48
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc420069a60, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/miekg/dns/server.go:84 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420069a50, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/miekg/dns/server.go:210 +0x65
github.com/miekg/dns.(*Server).serve(0xc420071790, 0xa9e6c0, 0xc421e5b4d0, 0xa9b240, 0xc420069a50, 0xc4222db200, 0x20, 0x200, 0xc420076200, 0xc421bbd4c0, ...)
	/root/go/src/github.com/miekg/dns/server.go:579 +0x2fb
created by github.com/miekg/dns.(*Server).serveUDP
	/root/go/src/github.com/miekg/dns/server.go:533 +0x2d5

**Comment by hawkingrei** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x697e6f]

goroutine 671582 [running]:
github.com/hawkingrei/g53/cache.(*MsgCache).Get(0xc42010e000, 0xc421916c70, 0xf, 0xc421bb0001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/hawkingrei/g53/cache/msglru.go:61 +0x1ef
github.com/hawkingrei/g53/servers/dnsutils.QueryDnsCache(0xc42010e000, 0xc420336360, 0xc42001e050, 0xc42001e000, 0xc422019bf0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsutils/dnsutils.go:25 +0xde
github.com/hawkingrei/g53/servers.(*DNSServer).queryDnsCache(0xc420116600, 0xc420336360, 0x0, 0x0, 0x0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:130 +0x39
github.com/hawkingrei/g53/servers.(*DNSServer).handleForward(0xc420116600, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:151 +0x58
github.com/hawkingrei/g53/servers.(*DNSServer).handleRequest(0xc420116600, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:314 +0x87e
github.com/hawkingrei/g53/servers.(*DNSServer).(github.com/hawkingrei/g53/servers.handleRequest)-fm(0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:56 +0x48
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc420069a60, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/miekg/dns/server.go:84 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420069a50, 0xaa53a0, 0xc4201c6b00, 0xc420336360)
	/root/go/src/github.com/miekg/dns/server.go:210 +0x65
github.com/miekg/dns.(*Server).serve(0xc420071790, 0xa9e6c0, 0xc421e5b4d0, 0xa9b240, 0xc420069a50, 0xc4222db200, 0x20, 0x200, 0xc420076200, 0xc421bbd4c0, ...)
	/root/go/src/github.com/miekg/dns/server.go:579 +0x2fb
created by github.com/miekg/dns.(*Server).serveUDP
	/root/go/src/github.com/miekg/dns/server.go:533 +0x2d5

**Comment by hawkingrei** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x697e6f]

goroutine 903731 [running]:
github.com/hawkingrei/g53/cache.(*MsgCache).Get(0xc4200f6000, 0xc4222ed800, 0x11, 0xc4222e0001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/hawkingrei/g53/cache/msglru.go:61 +0x1ef
github.com/hawkingrei/g53/servers/dnsutils.QueryDnsCache(0xc4200f6000, 0xc4212caab0, 0xc42001c050, 0xc42001c000, 0xc420039bf0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsutils/dnsutils.go:25 +0xde
github.com/hawkingrei/g53/servers.(*DNSServer).queryDnsCache(0xc4200fe630, 0xc4212caab0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:130 +0x39
github.com/hawkingrei/g53/servers.(*DNSServer).handleForward(0xc4200fe630, 0xaa53a0, 0xc42111da00, 0xc4212caab0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:151 +0x58
github.com/hawkingrei/g53/servers.(*DNSServer).handleRequest(0xc4200fe630, 0xaa53a0, 0xc42111da00, 0xc4212caab0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:314 +0x87e
github.com/hawkingrei/g53/servers.(*DNSServer).(github.com/hawkingrei/g53/servers.handleRequest)-fm(0xaa53a0, 0xc42111da00, 0xc4212caab0)
	/root/go/src/github.com/hawkingrei/g53/servers/dnsserver.go:56 +0x48
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc420013b30, 0xaa53a0, 0xc42111da00, 0xc4212caab0)
	/root/go/src/github.com/miekg/dns/server.go:84 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420013b20, 0xaa53a0, 0xc42111da00, 0xc4212caab0)
	/root/go/src/github.com/miekg/dns/server.go:210 +0x65
github.com/miekg/dns.(*Server).serve(0xc4200636c0, 0xa9e6c0, 0xc4222c2c00, 0xa9b240, 0xc420013b20, 0xc421bd8000, 0x22, 0x200, 0xc42000e208, 0xc4222ed700, ...)
	/root/go/src/github.com/miekg/dns/server.go:579 +0x2fb
created by github.com/miekg/dns.(*Server).serveUDP
	/root/go/src/github.com/miekg/dns/server.go:533 +0x2d5
